services:
  langdonguibe:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdongui.backend
      tags:
        - langdon_i
    volumes:
      - recon_volume:/recon
    networks:
      - gui_network

  langdonguife:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdongui.frontend
      tags:
        - langdonguife_i
    depends_on:
      - langdonguibe
    ports:
      - "8080:80"
    networks:
      - gui_network

networks:
  gui_network:
    driver: bridge

volumes:
  recon_volume:
