[tool.langdon]
cache_file = "/recon/.langdon.cache.json"
content_wordlist = "/root/SecLists/Discovery/Web-Content/raft-large-directories-lowercase.txt"
database = "/recon/langdon.db"
dns_wordlist = "/root/jhaddix/all.txt"
downloaded_apks_dir = "/recon/downloaded_apks"
event_queue_file = "/recon/.langdon.events.queue.json"
log_file = "/recon/langdon.log"
resolvers_file = "/root/massdns/lists/resolvers.txt"
socks_proxy_host = "tor"
socks_proxy_port = 9050
task_queue_file = "/recon/.langdon.tasks.queue.json"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0"
web_directory_screenshots = "/recon/web_screenshots"
